/*****************************************************************************
* Model: oregonPlayer.qm
* File:  ./oregonPlayer.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::oregonPlayer.h} .....................................................*/
#ifndef oregonPlayer_h
#define oregonPlayer_h
#ifdef __cplusplus
extern "C" {
#endif
#include "qhsm.h"    /* include own framework tagunil version */
#include "eventHandlers.h"
(do not delete this caption):
#import "EventHandlers.h"
#DEFINE HEALTHY 0
#DEFINE AGONY 1
#DEFINE DEAD 2
#DEFINE GHOUL-GOOD 3
#DEFINE GHOUL_WOUNDED 4
#DEFINE GHOUL_HEALING 5
#DEFINE BLESSED 6
...
#DEFINE FLASH_MS 300
#DEFINE TIMEOUT_AGONY_S 600
#DEFINE TIMEOUT_DEATH_S 15
#DEFINE TIMEOUT_RADX_S 900
#DEFINE LONG_BEEP_MS 15000
#DEFINE SHORT_BEEP_MS 500
#DEFINE DEFAULT_HP 27000
#DEFINE GHOUL_HP (DEFAULT_HP/3)

typedef struct oregonPlayerQEvt {
    QEvt super;
    unsigned int value;
} oregonPlayerQEvt;

enum PlayerSignals {
TICK_SEC_SIG = Q_USER_SIG,

TIME_TICK_1S_SIG,
HEAL_SIG,
RAD_RCVD_SIG,
GHOUL_HP)]_SIG,
TIME_TICK_10S_SIG,
TIME_TICK_1M_SIG,
AGONY_SIG,
IMMUNE_SIG,
PILL_GHOUL_SIG,
PILL_REMOVED_SIG,
NOT_IMMUNE_SIG,
BLESSED_SIG,
PILL_RESET_SIG,
PILL_TEST_SIG,

LAST_USER_SIG
};
extern QHsm * const the_oregonPlayer; /* opaque pointer to the oregonPlayer HSM */

/*${SMs::OregonPlayer_ctor} ................................................*/
void OregonPlayer_ctor(
    (do not delete this caption):,
    unsigned int HP,
    unsigned int Statunsigned,
    int TimerAgony);

#ifdef __cplusplus
}
#endif
#endif /* oregonPlayer_h */
